CREATE TABLE IF NOT EXISTS COMMENTARIES
(
 id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
 body VARCHAR (200) NOT NULL,
 created_date TIMESTAMP,
 user_id INTEGER,
 FOREIGN KEY (user_id) REFERENCES USERS(id)
);